package it.iks.openapm.models;

import org.springframework.data.annotation.Id;
import org.springframework.data.elasticsearch.annotations.Document;

import java.util.HashMap;
import java.util.Map;

/**
 * Remediation action configuration
 */
@Document(indexName = "#{@actionsConfigIndex}", type = "#{@actionsConfigType}")
public class ActionConfig {
    /**
     * Database identifier
     */
    @Id
    private String id;

    /**
     * Action human-readable name
     */
    private String name;

    /**
     * Action type (email, exec, etc)
     */
    private String type;

    /**
     * Custom action data
     */
    private Map<String, Object> data;

    /**
     * Initialize empty ActionConfig.
     */
    public ActionConfig() {
        this(null, null, null, new HashMap<>());
    }

    /**
     * Initialize ActionConfig.
     *
     * @param id   Database identifier
     * @param name Action human-readable name
     * @param type Action type (email, exec, etc)
     * @param data Custom action data
     */
    public ActionConfig(String id, String name, String type, Map<String, Object> data) {
        this.id = id;
        this.name = name;
        this.type = type;
        this.data = data;
    }

    /////////////////////////////// AUTOGENERATED METHODS ///////////////////////////////

    public String getId() {
        return id;
    }

    public ActionConfig setId(String id) {
        this.id = id;
        return this;
    }

    public String getName() {
        return name;
    }

    public ActionConfig setName(String name) {
        this.name = name;
        return this;
    }

    public String getType() {
        return type;
    }

    public ActionConfig setType(String type) {
        this.type = type;
        return this;
    }

    public Map<String, Object> getData() {
        return data;
    }

    public ActionConfig setData(Map<String, Object> data) {
        this.data = data;
        return this;
    }

    @Override
    public String toString() {
        return "ActionConfig{" +
                "id='" + id + '\'' +
                ", name='" + name + '\'' +
                ", type='" + type + '\'' +
                ", data=" + data +
                '}';
    }
}
