package it.iks.openapm.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import org.springframework.data.annotation.Id;
import org.springframework.data.elasticsearch.annotations.Document;

import java.util.Arrays;

/**
 * Alert checking configuration
 */
@Document(indexName = "#{@alertsConfigIndex}", type = "#{@alertsConfigType}")
public class AlertConfig {
    /**
     * Database identifier
     */
    @Id
    private String id;

    /**
     * Alert policy name
     */
    private String name;

    /**
     * Policy to use to evaluate conditions (match all, match any, etc)
     */
    @JsonProperty("evaluate_when")
    private String evaluateWhen;

    /**
     * List of conditions to match
     */
    private ConditionConfig[] conditions;

    /**
     * Verification event
     */
    private VerificationConfig verification;

    /**
     * Remediation actions to be triggered (as IDs)
     */
    private String[] actions;

    /**
     * Initialize empty AlertConfig.
     */
    public AlertConfig() {
        this(null, null, null, new ConditionConfig[]{}, null, new String[]{});
    }

    /**
     * Initialize AlertConfig.
     *
     * @param id           Database identifier
     * @param name         Alert policy name
     * @param evaluateWhen Policy to use to evaluate conditions
     * @param conditions   List of conditions to match
     * @param verification Verification event
     * @param actions      Remediation actions to be triggered (as IDs)
     */
    public AlertConfig(String id,
                       String name,
                       String evaluateWhen,
                       ConditionConfig[] conditions,
                       VerificationConfig verification,
                       String[] actions) {
        this.id = id;
        this.name = name;
        this.evaluateWhen = evaluateWhen;
        this.conditions = conditions;
        this.verification = verification;
        this.actions = actions;
    }

    /////////////////////////////// AUTOGENERATED METHODS ///////////////////////////////

    public String getId() {
        return id;
    }

    public AlertConfig setId(String id) {
        this.id = id;
        return this;
    }

    public String getName() {
        return name;
    }

    public AlertConfig setName(String name) {
        this.name = name;
        return this;
    }

    public String getEvaluateWhen() {
        return evaluateWhen;
    }

    public AlertConfig setEvaluateWhen(String evaluateWhen) {
        this.evaluateWhen = evaluateWhen;
        return this;
    }

    public ConditionConfig[] getConditions() {
        return conditions;
    }

    public AlertConfig setConditions(ConditionConfig[] conditions) {
        this.conditions = conditions;
        return this;
    }

    public VerificationConfig getVerification() {
        return verification;
    }

    public AlertConfig setVerification(VerificationConfig verification) {
        this.verification = verification;
        return this;
    }

    public String[] getActions() {
        return actions;
    }

    public AlertConfig setActions(String[] actions) {
        this.actions = actions;
        return this;
    }

    @Override
    public String toString() {
        return "AlertConfig{" +
                "id='" + id + '\'' +
                ", name='" + name + '\'' +
                ", evaluateWhen='" + evaluateWhen + '\'' +
                ", conditions=" + Arrays.toString(conditions) +
                ", verification=" + verification +
                ", actions=" + Arrays.toString(actions) +
                '}';
    }
}
