package it.iks.openapm.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import it.iks.openapm.models.contracts.AggregableConfig;
import it.iks.openapm.models.contracts.FilterableConfig;
import org.springframework.data.annotation.Id;
import org.springframework.data.elasticsearch.annotations.Document;

import java.util.Arrays;

/**
 * Baseline generation configuration
 */
@Document(indexName = "#{@baselinesConfigIndex}", type = "#{@baselinesConfigType}")
public class BaselineConfig implements AggregableConfig, FilterableConfig {
    /**
     * Database identifier
     */
    @Id
    private String id;

    /**
     * Baseline name in destination database
     */
    private String name;

    /**
     * Index/Table to fetch metrics from
     */
    @JsonProperty("metrics_index")
    private String metricsIndex;

    /**
     * Index/Table to save baselines into
     */
    @JsonProperty("baselines_index")
    private String baselinesIndex;

    /**
     * Baseline calculation strategy
     */
    private String strategy;

    /**
     * Set of operations to filter traces
     */
    private Operation[] filters;

    /**
     * Operation to aggregate traces into group before calculations
     */
    private Operation aggregation;

    /**
     * Field to grab metric value from
     */
    @JsonProperty("calculation_field")
    private String calculationField;

    /**
     * Initialize an empty baseline configuration
     */
    public BaselineConfig() {
        this(null, null, null, null, null, new Operation[]{}, null, null);
    }

    /**
     * Initialize a full-featured baseline configuration
     *
     * @param id
     * @param name
     * @param metricsIndex
     * @param baselinesIndex
     * @param strategy
     * @param filters
     * @param aggregation
     * @param calculationField
     */
    public BaselineConfig(String id,
                          String name,
                          String metricsIndex,
                          String baselinesIndex,
                          String strategy,
                          Operation[] filters,
                          Operation aggregation,
                          String calculationField) {
        this.id = id;
        this.name = name;
        this.metricsIndex = metricsIndex;
        this.baselinesIndex = baselinesIndex;
        this.strategy = strategy;
        this.filters = filters;
        this.aggregation = aggregation;
        this.calculationField = calculationField;
    }

    /////////////////////////////// AUTOGENERATED METHODS ///////////////////////////////

    public String getId() {
        return id;
    }

    public BaselineConfig setId(String id) {
        this.id = id;
        return this;
    }

    public String getName() {
        return name;
    }

    public BaselineConfig setName(String name) {
        this.name = name;
        return this;
    }

    public String getMetricsIndex() {
        return metricsIndex;
    }

    public BaselineConfig setMetricsIndex(String metricsIndex) {
        this.metricsIndex = metricsIndex;
        return this;
    }

    public String getBaselinesIndex() {
        return baselinesIndex;
    }

    public BaselineConfig setBaselinesIndex(String baselinesIndex) {
        this.baselinesIndex = baselinesIndex;
        return this;
    }

    public String getStrategy() {
        return strategy;
    }

    public BaselineConfig setStrategy(String strategy) {
        this.strategy = strategy;
        return this;
    }

    public Operation[] getFilters() {
        return filters;
    }

    public BaselineConfig setFilters(Operation[] filters) {
        this.filters = filters;
        return this;
    }

    public Operation getAggregation() {
        return aggregation;
    }

    public BaselineConfig setAggregation(Operation aggregation) {
        this.aggregation = aggregation;
        return this;
    }

    public String getCalculationField() {
        return calculationField;
    }

    public BaselineConfig setCalculationField(String calculationField) {
        this.calculationField = calculationField;
        return this;
    }

    @Override
    public String toString() {
        return "BaselineConfig{" +
                "id='" + id + '\'' +
                ", name='" + name + '\'' +
                ", metricsIndex='" + metricsIndex + '\'' +
                ", baselinesIndex='" + baselinesIndex + '\'' +
                ", strategy='" + strategy + '\'' +
                ", filters=" + Arrays.toString(filters) +
                ", aggregation=" + aggregation +
                ", calculationField='" + calculationField + '\'' +
                '}';
    }
}
