package it.iks.openapm.models;

import java.util.Arrays;

/**
 * Configuration object to fetch a baseline and calculate a value to use in policies
 */
public class BaselineValue {
    /**
     * Baseline index/table name
     */
    private String index;

    /**
     * List of filters to use to fetch the baseline
     */
    private Operation[] filters;

    /**
     * Baseline strategy to use as matcher
     */
    private String strategy;

    /**
     * Calculation to determine the value of the baseline to evaluate
     */
    private Operation calculation;

    /**
     * Initialize empty BaselineValue.
     */
    public BaselineValue() {
        this(null, new Operation[]{}, null, null);
    }

    /**
     * Initialize BaselineValue.
     *
     * @param index       Baseline index/table name
     * @param filters     List of filters to use to fetch the baseline
     * @param strategy    Baseline strategy to use as matcher
     * @param calculation Calculation to determine the value of the baseline to evaluate
     */
    public BaselineValue(String index, Operation[] filters, String strategy, Operation calculation) {
        this.index = index;
        this.filters = filters;
        this.strategy = strategy;
        this.calculation = calculation;
    }

    /////////////////////////////// AUTOGENERATED METHODS ///////////////////////////////


    public String getIndex() {
        return index;
    }

    public BaselineValue setIndex(String index) {
        this.index = index;
        return this;
    }

    public Operation[] getFilters() {
        return filters;
    }

    public BaselineValue setFilters(Operation[] filters) {
        this.filters = filters;
        return this;
    }

    public String getStrategy() {
        return strategy;
    }

    public BaselineValue setStrategy(String strategy) {
        this.strategy = strategy;
        return this;
    }

    public Operation getCalculation() {
        return calculation;
    }

    public BaselineValue setCalculation(Operation calculation) {
        this.calculation = calculation;
        return this;
    }

    @Override
    public String toString() {
        return "BaselineValue{" +
                "index='" + index + '\'' +
                ", filters=" + Arrays.toString(filters) +
                ", strategy='" + strategy + '\'' +
                ", calculation=" + calculation +
                '}';
    }
}
