package it.iks.openapm.models;

import java.util.Arrays;

/**
 * Policy for a single condition configuration
 */
public class ConditionConfig {
    /**
     * One or more metrics represented by a list of filters to retrieve them
     */
    private Operation[][] metrics;

    /**
     * Calculation to aggregate all metrics fields into a single result to evaluate
     */
    private Operation calculation;

    /**
     * Baseline retrieval configuration
     */
    private BaselineValue baseline;

    /**
     * Evaluation operation to determine if condition is matched
     */
    private Operation evaluation;

    /**
     * Initialize empty ConditionConfig.
     */
    public ConditionConfig() {
        this(new Operation[][]{}, null, null, null);
    }

    /**
     * Initialize ConditionConfig.
     *
     * @param metrics     One or more metrics represented by a list of filters to retrieve them
     * @param calculation Calculation to aggregate all metrics fields into a single result to evaluate
     * @param baseline    Baseline retrieval configuration
     * @param evaluation  Evaluation operation to determine if condition is matched
     */
    public ConditionConfig(Operation[][] metrics, Operation calculation, BaselineValue baseline, Operation evaluation) {
        this.metrics = metrics;
        this.calculation = calculation;
        this.baseline = baseline;
        this.evaluation = evaluation;
    }

    /////////////////////////////// AUTOGENERATED METHODS ///////////////////////////////

    public Operation[][] getMetrics() {
        return metrics;
    }

    public ConditionConfig setMetrics(Operation[][] metrics) {
        this.metrics = metrics;
        return this;
    }

    public Operation getCalculation() {
        return calculation;
    }

    public ConditionConfig setCalculation(Operation calculation) {
        this.calculation = calculation;
        return this;
    }

    public BaselineValue getBaseline() {
        return baseline;
    }

    public ConditionConfig setBaseline(BaselineValue baseline) {
        this.baseline = baseline;
        return this;
    }

    public Operation getEvaluation() {
        return evaluation;
    }

    public ConditionConfig setEvaluation(Operation evaluation) {
        this.evaluation = evaluation;
        return this;
    }

    @Override
    public String toString() {
        return "ConditionConfig{" +
                "metrics=" + Arrays.toString(metrics) +
                ", calculation=" + calculation +
                ", baseline=" + baseline +
                ", evaluation=" + evaluation +
                '}';
    }
}
