package it.iks.openapm.models;

import java.util.Arrays;

/**
 * Generic operation model to be stored into database
 */
public class Operation {
    /**
     * Operation's operands
     */
    private String[] operands;

    /**
     * Operation's operator
     */
    private String operator;

    /**
     * Build a null operation
     */
    public Operation() {
        this(new String[]{}, null);
    }

    /**
     * Build an operation with only operands
     *
     * @param operands
     */
    public Operation(String[] operands) {
        this(operands, null);
    }

    /**
     * Build standard operation
     *
     * @param operands
     * @param operator
     */
    public Operation(String[] operands, String operator) {
        this.operands = operands;
        this.operator = operator;
    }

    /////////////////////////////// AUTOGENERATED METHODS ///////////////////////////////

    public String[] getOperands() {
        return operands;
    }

    public Operation setOperands(String[] operands) {
        this.operands = operands;
        return this;
    }

    public String getOperator() {
        return operator;
    }

    public Operation setOperator(String operator) {
        this.operator = operator;
        return this;
    }

    @Override
    public String toString() {
        return "Operation{" +
                "operands=" + Arrays.toString(operands) +
                ", operator='" + operator + '\'' +
                '}';
    }
}
