package it.iks.openapm.models;

/**
 * Policy verification event configuration
 */
public class VerificationConfig {
    /**
     * When to trigger the events (immediately, after N seconds, etc)
     */
    private String on;

    /**
     * General amount for verification
     *
     * Usually an amount in seconds to express
     * a "after N seconds" confition.
     */
    private long amount;

    /**
     * Initialize empty VerificationConfig.
     */
    public VerificationConfig() {
        this(null, 0);
    }

    /**
     * Initialize VerificationConfig.
     *
     * @param on     When to trigger the events
     * @param amount General amount for verification
     */
    public VerificationConfig(String on, long amount) {
        this.on = on;
        this.amount = amount;
    }

    /////////////////////////////// AUTOGENERATED METHODS ///////////////////////////////

    public String getOn() {
        return on;
    }

    public VerificationConfig setOn(String on) {
        this.on = on;
        return this;
    }

    public long getAmount() {
        return amount;
    }

    public VerificationConfig setAmount(long amount) {
        this.amount = amount;
        return this;
    }

    @Override
    public String toString() {
        return "VerificationConfig{" +
                "on='" + on + '\'' +
                ", amount=" + amount +
                '}';
    }
}
