FROM openjdk:8-jdk-alpine

RUN apk update && \
    apk upgrade && \
    apk add --no-cache bash git openssh ca-certificates && \
    rm -rf /var/cache/apk/*

RUN git clone https://github.com/stagemonitor/spring-petclinic.git /app

WORKDIR /app

RUN sed -i "s/^stagemonitor\\.elasticsearch\\.url .*/stagemonitor.elasticsearch.url = http:\\/\\/elasticsearch:9200/" src/main/resources/stagemonitor.properties

RUN ./mvnw compile

ENTRYPOINT ["./mvnw", "spring-boot:run"]
